apiVersion: batch/v1
kind: Job
metadata:
  name: python-job
  namespace: fss-app
spec:
  template:
    metadata:
      labels:
        app: python-job
    spec:
      restartPolicy: Never
      containers:
      - name: python-worker
        image: python:3.11-slim
        command: ["python"]
        args: ["-c", "print('Hello from Python job!'); import time; time.sleep(10); print('Job completed successfully!')"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      backoffLimit: 3