apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

# patchesStrategicMerge:
#   - patch-replicas.yaml

images:
  - name: nginx
    newTag: latest
