apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fss-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fss-app
  template:
    metadata:
      labels:
        app: php-fss-app
    spec:
      containers:
      - name: php-fss-app
        # Image is intended to be overridden per-overlay via kustomize imageTransformer or patches
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
