apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - php-job.yaml
  - cronjob.yaml

# README: this base provides a PHP web app (Deployment + Service) and a periodic job (CronJob). Overlays should set image tags, replicas and namespace.

# commonLabels:
#   app.kubernetes.io/name: python-fss-app
#   app.kubernetes.io/version: "1.0.0"

# images:
#   - name: nginx
#     newName: nginx
#     newTag: latest
