apiVersion: batch/v1
kind: Job
metadata:
  name: php-job
spec:
  template:
    metadata:
      labels:
        app: php-job
    spec:
      restartPolicy: Never
      containers:
      - name: php-worker
        image: php:8.2-fpm
        command: ["php"]
        args: ["-r", "echo 'Hello from PHP job!'; echo 'Job completed successfully!';"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      backoffLimit: 3
