apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  phpnamespace: fss-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-leader-election
  phpnamespace: fss-app
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-leader-election
  phpnamespace: fss-app
subjects:
  - kind: ServiceAccount
    name: vault
    phpnamespace: fss-app
roleRef:
  kind: Role
  name: vault-leader-election
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  phpnamespace: fss-app
spec:
  type: ClusterIP
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: cluster
      port: 8201
      targetPort: 8201
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  phpnamespace: fss-app
spec:
  serviceName: "vault"
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: vault
          image: hashicorp/vault:1.15.0
          ports:
            - containerPort: 8200
            - containerPort: 8201
          env:
            - name: VAULT_LOCAL_CONFIG
              value: |
                {
                  "listener": {
                    "tcp": {
                      "address": "0.0.0.0:8200",
                      "tls_disable": 1
                    }
                  },
                  "storage": {
                    "raft": {
                      "path": "/vault/data"
                    }
                  },
                  "ui": true,
                  "disable_mlock": false,
                  "cluster_addr": "http://vault-0.vault:8201"
                }
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "vault operator step-down || true"]
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
