apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - python-job.yaml

commonLabels:
  app.kubernetes.io/name: fss-app
  app.kubernetes.io/version: "1.0.0"

images:
  - name: nginx
    newName: nginx
    newTag: latest
