apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- python
  - php
  - ingress.yaml
  # - postgres
  # - vault/vault2.yaml

# labels:
#   - pairs:
#       app.kubernetes.io/name: fss-app
#       app.kubernetes.io/version: "1.0.0"

# images:
#   - name: nginx
#     newName: nginx
#     newTag: latest
