apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fss-app-dev
  namespace: dev
spec:
  project: default
  source:
    repoURL: 'git@github.com:fabiossena/gitops.git'
    targetRevision: main
    path: overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    #namespace: fss-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
