apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/version: "15.0"
